### ISSUE TITLE
Losing package "pyrfabm"

### ISSUE THREAD

**Issue by tanqiu98** [RomeroBarata/human_object_interaction#1]
Hello, I'm following your excellent work. But the package "pyrfabm" used in train_utils.py is lost in your environment.yml, could you provide that? Many thanks.

**Comment by RomeroBarata** [comment]
Hi QTQ2021,

Thanks for your interest and sorry about the missing dependencies. I just fixed them with the latest commit.

Kind regards,
Romero

**Comment by tanqiu98** [comment]
Hi Romero,

Thanks for the correction! I'm really glad to continue to follow this work.

Best wishes,
QTQ
