### ISSUE TITLE
Fail to train

### ISSUE THREAD

**Issue by tanqiu98** [RomeroBarata/human_object_interaction#3]
Hi Romero,

When I tried to train the assign model, I changed the "_epochs_" in ./conf/models/assign.yaml, but I can't get any result. However, if I keep the default number "_epochs: 1_", it shows the outcome.

Kind regards,
QTQ

**Comment by RomeroBarata** [comment]
Hi QTQ,

Could you give me a bit more details of what happens when you try epochs > 1? I just tried to change the epochs value and everything works okay for me.

Kind regards,
Romero

**Comment by tanqiu98** [comment]
Hi Romero,

Thanks for the response. I also got the result of epoch=2 afterwards, but not for more epochs. I'm not sure if this is because the training time is too long. It would be very helpful if you can provide the number of epochs and batch size during training.

Many thanks,
QTQ

**Comment by RomeroBarata** [comment]
Hi QTQ,

Training can indeed take a while. I normally use 40 epochs and a batch size of 16. For the Bimanual dataset you can play with these values a bit (e.g. increase batch size and reduce number of epochs) since it is a bigger dataset and training takes even more time.

Kind regards,
Romero

**Comment by tanqiu98** [comment]
Hi Romero,

Got it. I am continuing to do this work, thanks for your suggestion.

Best wishes,
QTQ

**Comment by RomeroBarata** [comment]
Hi QTQ,

No worries.

Kind regards,
Romero
