### ISSUE TITLE
Results for four subjects

### ISSUE THREAD

**Issue by tanqiu98** [RomeroBarata/human_object_interaction#4]
Hi Romero,

I have a question about testing pre-trained models. When I run the code of "Evaluate ASSIGN on CAD-120 dataset:" in README.md, I can get the results of total four subjects. But when I test my pre-trained model, I can only get the result for a specified subject. I'd like to achieve the same pattern of results like you, to obtain the mean of F1@k in different tasks for four subjects.

Many thanks,
QTQ

**Comment by RomeroBarata** [comment]
Hi QTQ,

To get the results for all subjects you need to include the `--cross_validate` flag and make sure you have pre-trained all four models. When you add the `--cross_validate` flag, the code looks up for other pre-trained models in the same directory, with the same configuration but trained on different subsets of subjects, and runs them all to compute the averaged metrics.

For example, if you have a model XXX_Subject1 and pass it to `predict.py` with the flag `--cross_validate`, the code will search for the models XXX_Subject3, XXX_Subject4, and XXX_Subject5, and compute all results and averages from the models it could find.

Kind regards,
Romero

**Comment by tanqiu98** [comment]
Hi Romero,

Many thanks for your explanation. I also noticed that the name of the pre-trained model I got is different from yours. For exmaple, after training in stage 1 for subject 1, I got 
>hs512_e40_bs16_lr0.001_sc-None_h2h-False_h2o-True_o2h-True_o2o-True_m-v2-v1-att-v3-False-True_sd-0.5-False_os-ind_dn-1-gs_pf-e0s0_c0_sp-1_ihs-False_ios-False_al-1.0_bl-False-1.0-1.0_sl-False-False-0.0-1.0_fl0-0.0_mt-False_pt-False_gc0.0_ds3_Subject1

but the corresponding name of yours is 
>hs512_e40_bs16_lr0.001_sc-None_h2h-False_h2o-True_o2h-True_o2o-True_m-v2-v1-att-v3-False-True_sd-0.5-False_os-ind_dn-1-gs_pf-e00_c0_sp-1_ihs-False_ios-False_bl-False-1.0-1.0_sl-False-False-0.0-1.0_mt-False_pt-False_gc0.0_ds3_Subject1

So it seems like I have two more elements of "al-1.0" and "fl0-0.0" in the name of my pre-trained model.

Also, for the name of pre-trained model trained in stage 2 for subject 1, I got
>hs512_e40_bs16_lr0.001_sc-None_h2h-False_h2o-True_o2h-True_o2o-True_m-v2-v1-att-v3-False-True_sd-0.1-True_os-ind_dn-1-gs_pf-e0s0_c0_sp-0_ihs-False_ios-False_al-1.0_bl-False-1.0-1.0_sl-True-False-4.0-1.0_fl0-0.0_mt-False_pt-True_gc0.0_ds3_Subject1

and you have
>hs512_e40_bs16_lr0.001_sc-None_h2h-False_h2o-True_o2h-True_o2o-True_m-v2-v1-att-v3-False-True_sd-0.1-True_os-ind_dn-1-gs_pf-e0s0_c0_sp-0_ihs-False_ios-False_bl-False-1.0-1.0_sl-True-False-4.0-1.0_fl0-0.0_mt-False_pt-True-z_gc0.0_ds3_Subject1

In this case, yours still does not have "al-1.0" but has another additional element of "-z".

Best wishes,
QTQ

**Comment by RomeroBarata** [comment]
Hi QTQ,

The extra elements in the name of your pre-trained models are okay. These flags are related to some further investigations I did later; keeping their default values will match with the pre-trained models I provided. The "-z" in the second stage has no actual meaning; I added it manually to differentiate the final pre-trained model.

Kind regards,
Romero

**Comment by tanqiu98** [comment]
Hi Romero,

Yeah, this solved my question.

Cheers,
QTQ

**Comment by SISTMrL** [comment]
@QTQ2021 hello, could you please leave me a contact information, I have so much problems, can you help me? thanks!
