### ISSUE TITLE
training time and distribute training?

### ISSUE THREAD

**Issue by SISTMrL** [RomeroBarata/human_object_interaction#5]
hello, could you tell me the training time on CAD-120 dataset and BimanualActions dataset, and is this repo can run on only one gpu? could you release the multi-gpu version? looking forward to your reply, thanks!

**Comment by RomeroBarata** [comment]
Hi SISTMrL,

I cannot recall training time on the datasets, but I think it was roughly 6h on CAD-120 and a day on Bimanual (single V100). It also varies a bit depending on the cross-validation training subset you are using.

My implementation only takes advantage of a single GPU and I don't have a multi-GPU version of it, sorry.

Kind regards,
Romero

**Comment by SISTMrL** [comment]
Thanks for your reply!

**Comment by SISTMrL** [comment]
> Hi SISTMrL,
> 
> I cannot recall training time on the datasets, but I think it was roughly 6h on CAD-120 and a day on Bimanual (single V100). It also varies a bit depending on the cross-validation training subset you are using.
> 
> My implementation only takes advantage of a single GPU and I don't have a multi-GPU version of it, sorry.
> 
> Kind regards, Romero

Thanks for your reply!

**Comment by SISTMrL** [comment]
@RomeroBarata Thanks for your reply!
