### ISSUE TITLE
the parameters setting

### ISSUE THREAD

**Issue by SISTMrL** [RomeroBarata/human_object_interaction#6]
hello, in your released repo, the conf/model/assign.yaml's parameters setting is not same to your release trained model, such as epoch=1, hidden_size=2, they are not same as with your released trained model, should i modify them in assign.yaml and train the model to reproduce your results, looking forward to your reply, thanks!

**Comment by RomeroBarata** [comment]
Hi SISTMrL,

That's right, you have to modify the values in `assign.yaml`'s file to train a model similar to the pre-trained model provided.

**Comment by SISTMrL** [comment]
@RomeroBarata thanks for your reply
