### ISSUE TITLE
parameters problem  of reproduce

### ISSUE THREAD

**Issue by SISTMrL** [RomeroBarata/human_object_interaction#8]
hello, when i reproduce the assign, i found there is the params:"anticipation_loss_weight=1.0", but in your released trained model's config.yaml, i didn't see this params, and i can't reproduce the performance with your paper, could you give me some suggestions, looking forward to your reply, thanks!

**Comment by RomeroBarata** [comment]
Hi SISTMrL,

The released model has anticipation_loss_weight=1.0 even though it's not in the configuration. I added it as an option later for ablation studies, that's why it is missing from the released config.

**Comment by SISTMrL** [comment]
I see, thanks for explanation
